export type Gym = {
  number: number;
  name: string;
};

export type PokemonGame = {
  name: string;
  generation: number;
  gyms: Gym[];
};

export const POKEMON_GAMES: PokemonGame[] = [
  {
    name: "Pokémon Rojo",
    generation: 1,
    gyms: [
      { number: 1, name: "Gimnasio de Plateópolis (Brock)" },
      { number: 2, name: "Gimnasio de Celeste (Misty)" },
      { number: 3, name: "Gimnasio de Azafrán (Lt. Surge)" },
      { number: 4, name: "Gimnasio de Lavanda (Erika)" },
      { number: 5, name: "Gimnasio de Fucsia (Koga)" },
      { number: 6, name: "Gimnasio de Azulona (Sabrina)" },
      { number: 7, name: "Gimnasio de Carmín (Blaine)" },
      { number: 8, name: "Gimnasio de Viridian (Giovanni)" },
    ],
  },
  {
    name: "Pokémon Azul",
    generation: 1,
    gyms: [
      { number: 1, name: "Gimnasio de Plateópolis (Brock)" },
      { number: 2, name: "Gimnasio de Celeste (Misty)" },
      { number: 3, name: "Gimnasio de Azafrán (Lt. Surge)" },
      { number: 4, name: "Gimnasio de Lavanda (Erika)" },
      { number: 5, name: "Gimnasio de Fucsia (Koga)" },
      { number: 6, name: "Gimnasio de Azulona (Sabrina)" },
      { number: 7, name: "Gimnasio de Carmín (Blaine)" },
      { number: 8, name: "Gimnasio de Viridian (Giovanni)" },
    ],
  },
  {
    name: "Pokémon Amarillo",
    generation: 1,
    gyms: [
      { number: 1, name: "Gimnasio de Plateópolis (Brock)" },
      { number: 2, name: "Gimnasio de Celeste (Misty)" },
      { number: 3, name: "Gimnasio de Azafrán (Lt. Surge)" },
      { number: 4, name: "Gimnasio de Lavanda (Erika)" },
      { number: 5, name: "Gimnasio de Fucsia (Koga)" },
      { number: 6, name: "Gimnasio de Azulona (Sabrina)" },
      { number: 7, name: "Gimnasio de Carmín (Blaine)" },
      { number: 8, name: "Gimnasio de Viridian (Giovanni)" },
    ],
  },
  {
    name: "Pokémon Oro",
    generation: 2,
    gyms: [
      { number: 1, name: "Gimnasio de Olivo (Falkner)" },
      { number: 2, name: "Gimnasio de Azalea (Bugsy)" },
      { number: 3, name: "Gimnasio de Goldenrod (Whitney)" },
      { number: 4, name: "Gimnasio de Ecruteak (Morty)" },
      { number: 5, name: "Gimnasio de Cianwood (Chuck)" },
      { number: 6, name: "Gimnasio de Olivine (Jasmine)" },
      { number: 7, name: "Gimnasio de Mahogany (Pryce)" },
      { number: 8, name: "Gimnasio de Blackthorn (Clair)" },
    ],
  },
  {
    name: "Pokémon Plata",
    generation: 2,
    gyms: [
      { number: 1, name: "Gimnasio de Olivo (Falkner)" },
      { number: 2, name: "Gimnasio de Azalea (Bugsy)" },
      { number: 3, name: "Gimnasio de Goldenrod (Whitney)" },
      { number: 4, name: "Gimnasio de Ecruteak (Morty)" },
      { number: 5, name: "Gimnasio de Cianwood (Chuck)" },
      { number: 6, name: "Gimnasio de Olivine (Jasmine)" },
      { number: 7, name: "Gimnasio de Mahogany (Pryce)" },
      { number: 8, name: "Gimnasio de Blackthorn (Clair)" },
    ],
  },
  {
    name: "Pokémon Cristal",
    generation: 2,
    gyms: [
      { number: 1, name: "Gimnasio de Olivo (Falkner)" },
      { number: 2, name: "Gimnasio de Azalea (Bugsy)" },
      { number: 3, name: "Gimnasio de Goldenrod (Whitney)" },
      { number: 4, name: "Gimnasio de Ecruteak (Morty)" },
      { number: 5, name: "Gimnasio de Cianwood (Chuck)" },
      { number: 6, name: "Gimnasio de Olivine (Jasmine)" },
      { number: 7, name: "Gimnasio de Mahogany (Pryce)" },
      { number: 8, name: "Gimnasio de Blackthorn (Clair)" },
    ],
  },
  {
    name: "Pokémon Rubí",
    generation: 3,
    gyms: [
      { number: 1, name: "Gimnasio de Rustboro (Roxanne)" },
      { number: 2, name: "Gimnasio de Dewford (Brawly)" },
      { number: 3, name: "Gimnasio de Mauville (Wattson)" },
      { number: 4, name: "Gimnasio de Lavaridge (Flannery)" },
      { number: 5, name: "Gimnasio de Petalburg (Norman)" },
      { number: 6, name: "Gimnasio de Fortree (Winona)" },
      { number: 7, name: "Gimnasio de Mossdeep (Tate & Liza)" },
      { number: 8, name: "Gimnasio de Sootopolis (Wallace)" },
    ],
  },
  {
    name: "Pokémon Zafiro",
    generation: 3,
    gyms: [
      { number: 1, name: "Gimnasio de Rustboro (Roxanne)" },
      { number: 2, name: "Gimnasio de Dewford (Brawly)" },
      { number: 3, name: "Gimnasio de Mauville (Wattson)" },
      { number: 4, name: "Gimnasio de Lavaridge (Flannery)" },
      { number: 5, name: "Gimnasio de Petalburg (Norman)" },
      { number: 6, name: "Gimnasio de Fortree (Winona)" },
      { number: 7, name: "Gimnasio de Mossdeep (Tate & Liza)" },
      { number: 8, name: "Gimnasio de Sootopolis (Wallace)" },
    ],
  },
  {
    name: "Pokémon Esmeralda",
    generation: 3,
    gyms: [
      { number: 1, name: "Gimnasio de Rustboro (Roxanne)" },
      { number: 2, name: "Gimnasio de Dewford (Brawly)" },
      { number: 3, name: "Gimnasio de Mauville (Wattson)" },
      { number: 4, name: "Gimnasio de Lavaridge (Flannery)" },
      { number: 5, name: "Gimnasio de Petalburg (Norman)" },
      { number: 6, name: "Gimnasio de Fortree (Winona)" },
      { number: 7, name: "Gimnasio de Mossdeep (Tate & Liza)" },
      { number: 8, name: "Gimnasio de Sootopolis (Juan)" },
    ],
  },
  {
    name: "Pokémon FireRed",
    generation: 3,
    gyms: [
      { number: 1, name: "Gimnasio de Plateópolis (Brock)" },
      { number: 2, name: "Gimnasio de Celeste (Misty)" },
      { number: 3, name: "Gimnasio de Azafrán (Lt. Surge)" },
      { number: 4, name: "Gimnasio de Lavanda (Erika)" },
      { number: 5, name: "Gimnasio de Fucsia (Koga)" },
      { number: 6, name: "Gimnasio de Azulona (Sabrina)" },
      { number: 7, name: "Gimnasio de Carmín (Blaine)" },
      { number: 8, name: "Gimnasio de Viridian (Giovanni)" },
    ],
  },
  {
    name: "Pokémon LeafGreen",
    generation: 3,
    gyms: [
      { number: 1, name: "Gimnasio de Plateópolis (Brock)" },
      { number: 2, name: "Gimnasio de Celeste (Misty)" },
      { number: 3, name: "Gimnasio de Azafrán (Lt. Surge)" },
      { number: 4, name: "Gimnasio de Lavanda (Erika)" },
      { number: 5, name: "Gimnasio de Fucsia (Koga)" },
      { number: 6, name: "Gimnasio de Azulona (Sabrina)" },
      { number: 7, name: "Gimnasio de Carmín (Blaine)" },
      { number: 8, name: "Gimnasio de Viridian (Giovanni)" },
    ],
  },
  {
    name: "Pokémon Diamante",
    generation: 4,
    gyms: [
      { number: 1, name: "Gimnasio de Oreburgh (Roark)" },
      { number: 2, name: "Gimnasio de Eterna (Gardenia)" },
      { number: 3, name: "Gimnasio de Veilstone (Maylene)" },
      { number: 4, name: "Gimnasio de Pastoria (Crasher Wake)" },
      { number: 5, name: "Gimnasio de Hearthome (Fantina)" },
      { number: 6, name: "Gimnasio de Canalave (Byron)" },
      { number: 7, name: "Gimnasio de Snowpoint (Candice)" },
      { number: 8, name: "Gimnasio de Sunyshore (Volkner)" },
    ],
  },
  {
    name: "Pokémon Perla",
    generation: 4,
    gyms: [
      { number: 1, name: "Gimnasio de Oreburgh (Roark)" },
      { number: 2, name: "Gimnasio de Eterna (Gardenia)" },
      { number: 3, name: "Gimnasio de Veilstone (Maylene)" },
      { number: 4, name: "Gimnasio de Pastoria (Crasher Wake)" },
      { number: 5, name: "Gimnasio de Hearthome (Fantina)" },
      { number: 6, name: "Gimnasio de Canalave (Byron)" },
      { number: 7, name: "Gimnasio de Snowpoint (Candice)" },
      { number: 8, name: "Gimnasio de Sunyshore (Volkner)" },
    ],
  },
  {
    name: "Pokémon Platino",
    generation: 4,
    gyms: [
      { number: 1, name: "Gimnasio de Oreburgh (Roark)" },
      { number: 2, name: "Gimnasio de Eterna (Gardenia)" },
      { number: 3, name: "Gimnasio de Veilstone (Maylene)" },
      { number: 4, name: "Gimnasio de Pastoria (Crasher Wake)" },
      { number: 5, name: "Gimnasio de Hearthome (Fantina)" },
      { number: 6, name: "Gimnasio de Canalave (Byron)" },
      { number: 7, name: "Gimnasio de Snowpoint (Candice)" },
      { number: 8, name: "Gimnasio de Sunyshore (Volkner)" },
    ],
  },
  {
    name: "Pokémon HeartGold",
    generation: 4,
    gyms: [
      { number: 1, name: "Gimnasio de Olivo (Falkner)" },
      { number: 2, name: "Gimnasio de Azalea (Bugsy)" },
      { number: 3, name: "Gimnasio de Goldenrod (Whitney)" },
      { number: 4, name: "Gimnasio de Ecruteak (Morty)" },
      { number: 5, name: "Gimnasio de Cianwood (Chuck)" },
      { number: 6, name: "Gimnasio de Olivine (Jasmine)" },
      { number: 7, name: "Gimnasio de Mahogany (Pryce)" },
      { number: 8, name: "Gimnasio de Blackthorn (Clair)" },
    ],
  },
  {
    name: "Pokémon SoulSilver",
    generation: 4,
    gyms: [
      { number: 1, name: "Gimnasio de Olivo (Falkner)" },
      { number: 2, name: "Gimnasio de Azalea (Bugsy)" },
      { number: 3, name: "Gimnasio de Goldenrod (Whitney)" },
      { number: 4, name: "Gimnasio de Ecruteak (Morty)" },
      { number: 5, name: "Gimnasio de Cianwood (Chuck)" },
      { number: 6, name: "Gimnasio de Olivine (Jasmine)" },
      { number: 7, name: "Gimnasio de Mahogany (Pryce)" },
      { number: 8, name: "Gimnasio de Blackthorn (Clair)" },
    ],
  },
  {
    name: "Pokémon Negro",
    generation: 5,
    gyms: [
      { number: 1, name: "Gimnasio de Striaton (Cilan/Chili/Cress)" },
      { number: 2, name: "Gimnasio de Nacrene (Lenora)" },
      { number: 3, name: "Gimnasio de Castelia (Burgh)" },
      { number: 4, name: "Gimnasio de Nimbasa (Elesa)" },
      { number: 5, name: "Gimnasio de Driftveil (Clay)" },
      { number: 6, name: "Gimnasio de Mistralton (Skyla)" },
      { number: 7, name: "Gimnasio de Icirrus (Brycen)" },
      { number: 8, name: "Gimnasio de Opelucid (Drayden/Iris)" },
    ],
  },
  {
    name: "Pokémon Blanco",
    generation: 5,
    gyms: [
      { number: 1, name: "Gimnasio de Striaton (Cilan/Chili/Cress)" },
      { number: 2, name: "Gimnasio de Nacrene (Lenora)" },
      { number: 3, name: "Gimnasio de Castelia (Burgh)" },
      { number: 4, name: "Gimnasio de Nimbasa (Elesa)" },
      { number: 5, name: "Gimnasio de Driftveil (Clay)" },
      { number: 6, name: "Gimnasio de Mistralton (Skyla)" },
      { number: 7, name: "Gimnasio de Icirrus (Brycen)" },
      { number: 8, name: "Gimnasio de Opelucid (Drayden/Iris)" },
    ],
  },
  {
    name: "Pokémon Negro 2",
    generation: 5,
    gyms: [
      { number: 1, name: "Gimnasio de Virbank (Roxie)" },
      { number: 2, name: "Gimnasio de Castelia (Burgh)" },
      { number: 3, name: "Gimnasio de Nimbasa (Elesa)" },
      { number: 4, name: "Gimnasio de Driftveil (Clay)" },
      { number: 5, name: "Gimnasio de Mistralton (Skyla)" },
      { number: 6, name: "Gimnasio de Humilau (Marlon)" },
      { number: 7, name: "Gimnasio de Icirrus (Brycen)" },
      { number: 8, name: "Gimnasio de Opelucid (Drayden)" },
    ],
  },
  {
    name: "Pokémon Blanco 2",
    generation: 5,
    gyms: [
      { number: 1, name: "Gimnasio de Virbank (Roxie)" },
      { number: 2, name: "Gimnasio de Castelia (Burgh)" },
      { number: 3, name: "Gimnasio de Nimbasa (Elesa)" },
      { number: 4, name: "Gimnasio de Driftveil (Clay)" },
      { number: 5, name: "Gimnasio de Mistralton (Skyla)" },
      { number: 6, name: "Gimnasio de Humilau (Marlon)" },
      { number: 7, name: "Gimnasio de Icirrus (Brycen)" },
      { number: 8, name: "Gimnasio de Opelucid (Drayden)" },
    ],
  },
  {
    name: "Pokémon X",
    generation: 6,
    gyms: [
      { number: 1, name: "Gimnasio de Santalune (Viola)" },
      { number: 2, name: "Gimnasio de Cyllage (Grant)" },
      { number: 3, name: "Gimnasio de Shalour (Korrina)" },
      { number: 4, name: "Gimnasio de Coumarine (Ramos)" },
      { number: 5, name: "Gimnasio de Lumiose (Clemont)" },
      { number: 6, name: "Gimnasio de Laverre (Valerie)" },
      { number: 7, name: "Gimnasio de Anistar (Olympia)" },
      { number: 8, name: "Gimnasio de Snowbelle (Wulfric)" },
    ],
  },
  {
    name: "Pokémon Y",
    generation: 6,
    gyms: [
      { number: 1, name: "Gimnasio de Santalune (Viola)" },
      { number: 2, name: "Gimnasio de Cyllage (Grant)" },
      { number: 3, name: "Gimnasio de Shalour (Korrina)" },
      { number: 4, name: "Gimnasio de Coumarine (Ramos)" },
      { number: 5, name: "Gimnasio de Lumiose (Clemont)" },
      { number: 6, name: "Gimnasio de Laverre (Valerie)" },
      { number: 7, name: "Gimnasio de Anistar (Olympia)" },
      { number: 8, name: "Gimnasio de Snowbelle (Wulfric)" },
    ],
  },
  {
    name: "Pokémon Rubí Omega",
    generation: 6,
    gyms: [
      { number: 1, name: "Gimnasio de Rustboro (Roxanne)" },
      { number: 2, name: "Gimnasio de Dewford (Brawly)" },
      { number: 3, name: "Gimnasio de Mauville (Wattson)" },
      { number: 4, name: "Gimnasio de Lavaridge (Flannery)" },
      { number: 5, name: "Gimnasio de Petalburg (Norman)" },
      { number: 6, name: "Gimnasio de Fortree (Winona)" },
      { number: 7, name: "Gimnasio de Mossdeep (Tate & Liza)" },
      { number: 8, name: "Gimnasio de Sootopolis (Juan)" },
    ],
  },
  {
    name: "Pokémon Zafiro Alfa",
    generation: 6,
    gyms: [
      { number: 1, name: "Gimnasio de Rustboro (Roxanne)" },
      { number: 2, name: "Gimnasio de Dewford (Brawly)" },
      { number: 3, name: "Gimnasio de Mauville (Wattson)" },
      { number: 4, name: "Gimnasio de Lavaridge (Flannery)" },
      { number: 5, name: "Gimnasio de Petalburg (Norman)" },
      { number: 6, name: "Gimnasio de Fortree (Winona)" },
      { number: 7, name: "Gimnasio de Mossdeep (Tate & Liza)" },
      { number: 8, name: "Gimnasio de Sootopolis (Juan)" },
    ],
  },
  {
    name: "Pokémon Sol",
    generation: 7,
    gyms: [
      { number: 1, name: "Gran prueba de Melemele (Ilima)" },
      { number: 2, name: "Gran prueba de Akala (Lana/Kiawe/Mallow)" },
      { number: 3, name: "Gran prueba de Ula'ula (Sophocles/Acerola)" },
      { number: 4, name: "Gran prueba de Poni (Hapu)" },
    ],
  },
  {
    name: "Pokémon Luna",
    generation: 7,
    gyms: [
      { number: 1, name: "Gran prueba de Melemele (Ilima)" },
      { number: 2, name: "Gran prueba de Akala (Lana/Kiawe/Mallow)" },
      { number: 3, name: "Gran prueba de Ula'ula (Sophocles/Acerola)" },
      { number: 4, name: "Gran prueba de Poni (Hapu)" },
    ],
  },
  {
    name: "Pokémon Ultrasol",
    generation: 7,
    gyms: [
      { number: 1, name: "Gran prueba de Melemele (Ilima)" },
      { number: 2, name: "Gran prueba de Akala (Lana/Kiawe/Mallow)" },
      { number: 3, name: "Gran prueba de Ula'ula (Sophocles/Acerola)" },
      { number: 4, name: "Gran prueba de Poni (Hapu)" },
    ],
  },
  {
    name: "Pokémon Ultraluna",
    generation: 7,
    gyms: [
      { number: 1, name: "Gran prueba de Melemele (Ilima)" },
      { number: 2, name: "Gran prueba de Akala (Lana/Kiawe/Mallow)" },
      { number: 3, name: "Gran prueba de Ula'ula (Sophocles/Acerola)" },
      { number: 4, name: "Gran prueba de Poni (Hapu)" },
    ],
  },
  {
    name: "Pokémon Espada",
    generation: 8,
    gyms: [
      { number: 1, name: "Gimnasio de Turffield (Milo)" },
      { number: 2, name: "Gimnasio de Hulbury (Nessa)" },
      { number: 3, name: "Gimnasio de Motostoke (Kabu)" },
      { number: 4, name: "Gimnasio de Stow-on-Side (Bea)" },
      { number: 5, name: "Gimnasio de Ballonlea (Opal)" },
      { number: 6, name: "Gimnasio de Circhester (Gordie)" },
      { number: 7, name: "Gimnasio de Spikemuth (Piers)" },
      { number: 8, name: "Gimnasio de Hammerlocke (Raihan)" },
    ],
  },
  {
    name: "Pokémon Escudo",
    generation: 8,
    gyms: [
      { number: 1, name: "Gimnasio de Turffield (Milo)" },
      { number: 2, name: "Gimnasio de Hulbury (Nessa)" },
      { number: 3, name: "Gimnasio de Motostoke (Kabu)" },
      { number: 4, name: "Gimnasio de Stow-on-Side (Allister)" },
      { number: 5, name: "Gimnasio de Ballonlea (Opal)" },
      { number: 6, name: "Gimnasio de Circhester (Melony)" },
      { number: 7, name: "Gimnasio de Spikemuth (Piers)" },
      { number: 8, name: "Gimnasio de Hammerlocke (Raihan)" },
    ],
  },
  {
    name: "Pokémon Diamante Brillante",
    generation: 8,
    gyms: [
      { number: 1, name: "Gimnasio de Oreburgh (Roark)" },
      { number: 2, name: "Gimnasio de Eterna (Gardenia)" },
      { number: 3, name: "Gimnasio de Veilstone (Maylene)" },
      { number: 4, name: "Gimnasio de Pastoria (Crasher Wake)" },
      { number: 5, name: "Gimnasio de Hearthome (Fantina)" },
      { number: 6, name: "Gimnasio de Canalave (Byron)" },
      { number: 7, name: "Gimnasio de Snowpoint (Candice)" },
      { number: 8, name: "Gimnasio de Sunyshore (Volkner)" },
    ],
  },
  {
    name: "Pokémon Perla Reluciente",
    generation: 8,
    gyms: [
      { number: 1, name: "Gimnasio de Oreburgh (Roark)" },
      { number: 2, name: "Gimnasio de Eterna (Gardenia)" },
      { number: 3, name: "Gimnasio de Veilstone (Maylene)" },
      { number: 4, name: "Gimnasio de Pastoria (Crasher Wake)" },
      { number: 5, name: "Gimnasio de Hearthome (Fantina)" },
      { number: 6, name: "Gimnasio de Canalave (Byron)" },
      { number: 7, name: "Gimnasio de Snowpoint (Candice)" },
      { number: 8, name: "Gimnasio de Sunyshore (Volkner)" },
    ],
  },
  {
    name: "Leyendas Pokémon: Arceus",
    generation: 8,
    gyms: [
      { number: 1, name: "Noble Kleavor (Lian)" },
      { number: 2, name: "Noble Lilligant (Calaba)" },
      { number: 3, name: "Noble Electrode (Ingo)" },
      { number: 4, name: "Noble Avalugg (Gaeric)" },
      { number: 5, name: "Noble Arcanine (Iscan)" },
    ],
  },
  {
    name: "Pokémon Escarlata",
    generation: 9,
    gyms: [
      { number: 1, name: "Gimnasio de Cortondo (Katy)" },
      { number: 2, name: "Gimnasio de Artazon (Brassius)" },
      { number: 3, name: "Gimnasio de Levincia (Iono)" },
      { number: 4, name: "Gimnasio de Cascarrafa (Kofu)" },
      { number: 5, name: "Gimnasio de Medali (Larry)" },
      { number: 6, name: "Gimnasio de Montenevera (Ryme)" },
      { number: 7, name: "Gimnasio de Alfornada (Tulip)" },
      { number: 8, name: "Gimnasio de Glaseado (Grusha)" },
    ],
  },
  {
    name: "Pokémon Púrpura",
    generation: 9,
    gyms: [
      { number: 1, name: "Gimnasio de Cortondo (Katy)" },
      { number: 2, name: "Gimnasio de Artazon (Brassius)" },
      { number: 3, name: "Gimnasio de Levincia (Iono)" },
      { number: 4, name: "Gimnasio de Cascarrafa (Kofu)" },
      { number: 5, name: "Gimnasio de Medali (Larry)" },
      { number: 6, name: "Gimnasio de Montenevera (Ryme)" },
      { number: 7, name: "Gimnasio de Alfornada (Tulip)" },
      { number: 8, name: "Gimnasio de Glaseado (Grusha)" },
    ],
  },
];
